### ISSUE TITLE
实现Promise.all有个错误

### ISSUE THREAD

**Issue by ascodelife** [Mayandev/fe-interview-handwrite#7]
res.length === arr.length
这一句，并不能保证所有promise都resolve了
若res[1]=1,则res.length=2;
但res[0]对应的promise不一定resolve了。

**Comment by Mayandev** [comment]
一个 promise 失败了就全部 reject，符合预期

**Comment by lincycode** [comment]
并不符合预期, 使用以下p1,p2作为例子就知道问题所在了, p1没有resolve的时候就到p2执行res[1] = 1导致最终结果变为[empty,1]
const p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('hello');
  }, 500);
});
let p2 = Promise.resolve(1);
